[build]
  command = "npm run build"
  publish="https://github.com/vesa193/hacker-news/build"
  base = "https://github.com/vesa193/hacker-news"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200